services:
  server:
    container_name: wos-backend
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - wos_backend_node_modules:/app/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - postgres-primary
      - postgres-replica
      - redis
    restart: unless-stopped
  client:
    container_name: wos-frontend
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - ./frontend:/app
      - wos_frontend_node_modules:/app/node_modules
    env_file:
      - ./frontend/.env
    restart: unless-stopped
  postgres-primary:
    image: bitnami/postgresql:latest
    container_name: wos-postgres-primary
    restart: always
    ports:
      - "5472:5432"
    volumes:
      - postgres_primary_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=123456
      - POSTGRESQL_DATABASE=wso-local
  postgres-replica:
    image: bitnami/postgresql:latest
    container_name: wos-postgres-replica
    restart: always
    ports:
      - "5473:5432"
    depends_on:
      - postgres-primary
    volumes:
      - postgres_replica_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=postgres-primary
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_PASSWORD=123456
  minio:
    image: quay.io/minio/minio:latest
    container_name: wos-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - ./backend/.env

    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: wos-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
volumes:
  postgres_primary_data:
  postgres_replica_data:
  minio_data:
  wos_backend_node_modules:
  wos_frontend_node_modules:
